<a href="https://colab.research.google.com/github/mateus-bombassaro/python-ai-colab/blob/main/Aula_1_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Rodando IA no Google Colab

In [ ]:
import os

from google.colab import userdata
userdata.get('GEMINI_API_KEY')

os.environ['GEMINI_API_KEY'] = userdata.get('GEMINI_API_KEY')

In [ ]:
from google import genai

client = genai.Client()

In [ ]:
resposta = client.models.generate_content(model="gemini-2.5-flash", contents="O que é a Inteligência Artificial?")

In [ ]:
print(resposta.text)

A **Inteligência Artificial (IA)** é um campo da ciência da computação que se dedica à criação de sistemas e máquinas capazes de realizar tarefas que, normalmente, exigiriam inteligência humana. O objetivo central da IA é simular ou imitar a capacidade de raciocínio, aprendizado, resolução de problemas, percepção e compreensão da linguagem humana.

Em outras palavras, é a capacidade de máquinas de "pensar" e "aprender" de forma semelhante aos seres humanos.

### Componentes Chave da IA:

1.  **Aprendizado (Machine Learning - ML):** É a capacidade de os sistemas aprenderem a partir de dados, identificar padrões e tomar decisões com intervenção humana mínima. Em vez de serem programados para cada tarefa específica, eles "treinam" com grandes volumes de dados.
    *   **Aprendizado Profundo (Deep Learning - DL):** Uma subárea do Machine Learning que utiliza redes neurais artificiais com muitas camadas (daí "profundo"), inspiradas no cérebro humano, para aprender e processar dados complexos, como imagens, sons e texto.

2.  **Raciocínio:** A capacidade de um sistema de IA de tirar conclusões lógicas a partir de informações disponíveis e aplicar esse conhecimento para resolver problemas.

3.  **Resolução de Problemas:** A habilidade de encontrar soluções para desafios, muitas vezes complexos, usando algoritmos e dados.

4.  **Percepção:** A capacidade de sistemas de IA de interpretar informações do ambiente, como visão (reconhecimento de imagem), audição (reconhecimento de fala) e até tato.

5.  **Compreensão da Linguagem Natural (Natural Language Processing - NLP):** Permite que as máquinas entendam, interpretem e gerem linguagem humana, tornando possível a comunicação entre humanos e computadores de forma mais natural (ex: assistentes de voz, chatbots).

### Tipos de IA:

Geralmente, a IA é categorizada em três níveis, embora apenas o primeiro seja amplamente realizado hoje:

1.  **IA Fraca ou Estreita (Narrow AI / Weak AI):** É o tipo de IA que existe atualmente. É projetada e treinada para uma tarefa específica. Não possui consciência, emoção ou inteligência geral.
    *   **Exemplos:** Assistentes de voz (Siri, Alexa), sistemas de recomendação (Netflix, Amazon), carros autônomos, filtros de spam, reconhecimento facial.

2.  **IA Geral (General AI / Strong AI):** É uma IA hipotética que possui a capacidade intelectual de um ser humano em qualquer tarefa. Ela seria capaz de aprender, compreender e aplicar sua inteligência a qualquer problema, assim como um ser humano. Ainda não existe.

3.  **Superinteligência Artificial (Artificial Superintelligence - ASI):** Uma IA hipotética que excede em muito a inteligência humana em todos os aspectos, incluindo criatividade, resolução de problemas e habilidades sociais. Ainda mais distante no futuro.

### Aplicações da IA:

A IA está presente em diversas áreas do nosso dia a dia:

*   **Saúde:** Diagnóstico de doenças, descoberta de medicamentos, robótica cirúrgica.
*   **Finanças:** Detecção de fraudes, negociação algorítmica, análise de risco.
*   **Varejo:** Recomendações personalizadas, otimização de estoque, atendimento ao cliente (chatbots).
*   **Transporte:** Carros autônomos, otimização de rotas.
*   **Educação:** Tutoria personalizada, sistemas de avaliação.
*   **Entretenimento:** Geração de conteúdo (música, arte, texto), jogos.
*   **Indústria:** Robótica, manutenção preditiva.

Em resumo, a Inteligência Artificial é um campo dinâmico e em constante evolução que busca dotar máquinas com capacidades intelectuais, transformando a maneira como vivemos e trabalhamos.

# Estruturas de Repetição, Loops, Laços

In [ ]:
n = 1
texto = ""
while n <= 10:
  texto = texto + "*"
  n = n + 1
print(texto)

**********

# Dinâmica de chatbots e histórico de mensagens

In [ ]:
chat = client.chats.create(model="gemini-2.5-flash")

In [ ]:
resposta = chat.send_message("O que é inteligencia artificial")

ServerError: 503 UNAVAILABLE. {'error': {'code': 503, 'message': 'This model is currently experiencing high demand. Spikes in demand are usually temporary. Please try again later.', 'status': 'UNAVAILABLE'}}

In [ ]:
print(resposta.text)

In [ ]:
chat.send_message("Quando foi lançado o chat GPT?")

In [ ]:
chat.get_history()

# Criando chatbot com Python e Gemini IA

In [ ]:
prompt = input("Digite o seu prompt: ")

while prompt != "sair":
  resposta = chat.send_message(prompt)
  print(resposta.text)
  prompt = input("Digite o seu prompt: ")

# Estrutura de Dados

Listas

In [ ]:
lista_de_nome = ["Ana Silva", "Bruno Costa", "Carla Santos", "Daniel Oliveira",
    "Erica Souza", "Felipe Pereira"]

In [ ]:
print(lista_de_nome[2])

In [ ]:
lista_de_medias = [8.9, 7.5, 4.2, 1.4, 9.5]

In [ ]:
print(lista_de_medias[3])

Desafio crie um código que percorra a lista e some 1 ponto, exceto quando o valor passar de 10, nota máxima

In [ ]:
n = 0
while n < 5:
  if lista_de_medias[n] + 1 <= 10:
    lista_de_medias[n] = lista_de_medias[n] + 1
  else:
    lista_de_medias[n] = 10
  n += 1
print(lista_de_medias)

In [ ]:
print(len(lista_de_medias))

Usar dicionarios de forma que as chaves sejam nome e nota e valores sejam nomes e medias

In [ ]:
dicio = {"Ana Silva": 8.9, "Bruno Costa": 7.5, "Carla Santos": 4.2, "Daniel Oliveira": 1.4, "Erica Souza": 9.5}

In [ ]:
dicio_desafio = [
    {"nome": "Ana Silva", "media": 8.9},
    {"nome": "Bruno Costa", "media": 7.5},
    {"nome": "Carla Santos", "media": 4.2},
    {"nome": "Daniel Oliveira", "media": 1.4},
    {"nome": "Erica Souza", "media": 9.5}
]

In [ ]:
dicio_desafio[0]["media"]

# Estrutura de repetição FOR

In [ ]:
dicio_desafio = [
    {"nome": "Ana Silva", "media": 8.9},
    {"nome": "Bruno Costa", "media": 7.5},
    {"nome": "Carla Santos", "media": 4.2},
    {"nome": "Daniel Oliveira", "media": 1.4},
    {"nome": "Erica Souza", "media": 9.5}
]

In [ ]:
for elemento in dicio_desafio:
  print(elemento["nome"])

In [ ]:
for n in range(5):
  print(n)

In [ ]:
for n in range(0, 10, 2):
  print(n)

In [ ]:
pessoa = {
    "nome": "João",
    "idade": 30,
    "cidade": "São Paulo"
}

for chave, valor in pessoa.items():
    print(chave, ":", valor)

In [ ]:
for n in range(11):
  if(n % 2 == 0):
      print(n)

# Funções

In [ ]:
texto2 = "anA SiLVa"
texto3 = "bRuNo  CoSta"
texto4 = "cARla      SAntoS"
texto5 = "daniEL  OLiveirA      "
texto6 = "erIcA SouzA"

In [ ]:
def escreve_texto_corretamente(texto):
  return " ".join(texto.upper().split())

In [ ]:
escreve_texto_corretamente(texto2)

In [ ]:
salas_de_aula = ["Sala 1", "Sala 2", "Sala 3"]

In [ ]:
import random

def aloca_alunos_em_salas(nome_do_aluno, salas_de_aula):
  sala_do_aluno = random.choice(salas_de_aula)
  dict_aluno = {
      "nome": escreve_texto_corretamente(nome_do_aluno),
      "sala": sala_do_aluno
  }
  return dict_aluno

print(aloca_alunos_em_salas(texto3, salas_de_aula))

Desafio:
1. Pedir para IA gerar em python uma lista de 20 emails
2. Criar função que vai receber como parâmetro uma lista de emails, percorrer, para cada email vai chamar a IA do Gemini resumir o email em apenas uma linha, definindo o que essa pessoa queria no email.

In [ ]:
def email_resume(emails_list):
  lista_de_resumos = []
  for numero, email in enumerate(emails_list):
    resposta = client.models.generate_content(
      model="gemini-2.5-flash",
      contents=f"""Vou te mandar o corpo de um email, quero que você o
        resuma em apenas 1 linha, segue o email: {email}"""
      )
    print(f"Email {numero + 1}: {resposta.text}")
    lista_de_resumos.append(f"Email {numero + 1}: {resposta.text}")
    print("-" * 50)

  return lista_de_resumos

In [ ]:
emails_corpo = [
    # 1. Email Comercial
    """Prezado(a) [Nome],

Espero que esteja bem. Entrei em contato para apresentar nossos serviços que podem contribuir significativamente para o crescimento do seu negócio. Possuímos uma equipe experiente pronta para atender suas necessidades.

Fico à disposição para agendar uma reunião e discutir como podemos colaborar.

Atenciosamente,
[Seu Nome]""",

    # 2. Email de Oportunidade de Emprego
    """Olá [Nome],

Vimos seu currículo e ficamos impressionados com sua experiência. Gostaríamos de convidá-lo(a) para participar do processo de seleção para a posição de [Cargo] em nossa empresa.

Por favor, confirme sua disponibilidade para uma entrevista preliminar.

Aguardamos seu retorno.

Atenciosamente,
Departamento de Recursos Humanos""",

    # 3. Email de Confirmação de Pedido
    """Caro(a) [Nome],

Agradecemos seu pedido! Confirmamos que recebemos seu pedido nº [Número] realizado em [Data].

Seu pedido será processado e você receberá atualizações sobre o status do envio em breve.

Obrigado pela preferência!

Atenciosamente,
Equipe de Vendas""",
]

lista_resumos = email_resume(emails_corpo)
print(lista_resumos)

Email 1: Agende uma reunião para apresentarmos nossos serviços e discutir como impulsionar o crescimento do seu negócio.
--------------------------------------------------
Email 2: O RH convida para o processo seletivo da vaga de [Cargo], pedindo para confirmar disponibilidade para uma entrevista.
--------------------------------------------------
Email 3: Agradecemos e confirmamos o recebimento do seu pedido, que será processado e o envio atualizado em breve.
--------------------------------------------------
['Email 1: Agende uma reunião para apresentarmos nossos serviços e discutir como impulsionar o crescimento do seu negócio.', 'Email 2: O RH convida para o processo seletivo da vaga de [Cargo], pedindo para confirmar disponibilidade para uma entrevista.', 'Email 3: Agradecemos e confirmamos o recebimento do seu pedido, que será processado e o envio atualizado em breve.']

# Open Source LLM

In [ ]:
!pip install -q groq

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.7/143.7 kB 3.6 MB/s eta 0:00:00

In [ ]:
from groq import Groq

client = Groq()
completion = client.chat.completions.create(
    model="openai/gpt-oss-120b",
    messages=[
      {
        "role": "user",
        "content": ""
      }
    ],
    temperature=1,
    max_completion_tokens=8192,
    top_p=1,
    reasoning_effort="medium",
    stream=True,
    stop=None
)

for chunk in completion:
    print(chunk.choices[0].delta.content or "", end="")

# Lendo e escrevendo arquivos com python

In [ ]:
with open("lista-de-resumos.text", 'w', encoding="utf-8") as arquivo:
  for element in lista_resumos:
    arquivo.write(element + "\n")

In [ ]:
lista_from_arquivo = []
with open("lista-de-resumos.text", 'r', encoding="utf-8") as arquivo:
  for linha in arquivo:
    lista_from_arquivo.append(linha)

print(lista_from_arquivo)

['Email 1: Agende uma reunião para apresentarmos nossos serviços e discutir como impulsionar o crescimento do seu negócio.\n', 'Email 2: O RH convida para o processo seletivo da vaga de [Cargo], pedindo para confirmar disponibilidade para uma entrevista.\n', 'Email 3: Agradecemos e confirmamos o recebimento do seu pedido, que será processado e o envio atualizado em breve.\n']

In [ ]:
conteudo = ''
with open("lista-de-resumos.text", 'r', encoding="utf-8") as arquivo:
  conteudo = arquivo.read()

print(conteudo)

Email 1: Agende uma reunião para apresentarmos nossos serviços e discutir como impulsionar o crescimento do seu negócio.
Email 2: O RH convida para o processo seletivo da vaga de [Cargo], pedindo para confirmar disponibilidade para uma entrevista.
Email 3: Agradecemos e confirmamos o recebimento do seu pedido, que será processado e o envio atualizado em breve.

In [ ]:
nova_lista_leitura_dois = []

with open("lista-de-resumos.text", 'r', encoding="utf-8") as arquivo:
  nova_lista_leitura_dois = arquivo.readlines()

print(nova_lista_leitura_dois)

['Email 1: Agende uma reunião para apresentarmos nossos serviços e discutir como impulsionar o crescimento do seu negócio.\n', 'Email 2: O RH convida para o processo seletivo da vaga de [Cargo], pedindo para confirmar disponibilidade para uma entrevista.\n', 'Email 3: Agradecemos e confirmamos o recebimento do seu pedido, que será processado e o envio atualizado em breve.\n']

# Pandas

In [2]:
import pandas as pd

In [ ]:
df = pd.read_csv("content/meu_csv.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'content/meu_csv.csv'

# Manipular dados com Panda

In [3]:
import numpy as np

# Gerar 50 linhas de dados
n_rows = 50

# Nomes de produtos aleatórios
product_names = [f'Produto {i+1}' for i in range(n_rows)]

# Categorias de produtos
categories = ['Eletrônicos', 'Alimentos', 'Vestuário', 'Livros', 'Casa']
product_categories = np.random.choice(categories, n_rows)

# Preços aleatórios entre 10 e 1000
prices = np.round(np.random.uniform(10, 1000, n_rows), 2)

# Quantidade de produtos vendidos aleatória entre 1 e 100
quantities_sold = np.random.randint(1, 101, n_rows)

# Criar o DataFrame
df_produtos = pd.DataFrame({
    'Nome do produto': product_names,
    'Categoria do produto': product_categories,
    'Preço': prices,
    'Quantos produtos foram vendidos': quantities_sold
})

display(df_produtos.head())

,Nome do produto,Categoria do produto,Preço,Quantos produtos foram vendidos
0,Produto 1,Alimentos,406.86,55
1,Produto 2,Alimentos,347.76,16
2,Produto 3,Alimentos,541.36,76
3,Produto 4,Eletrônicos,714.87,18
4,Produto 5,Vestuário,162.54,81

In [4]:
df_produtos["Categoria do produto"]

0       Alimentos
1       Alimentos
2       Alimentos
3     Eletrônicos
4       Vestuário
5          Livros
6     Eletrônicos
7       Alimentos
8          Livros
9            Casa
10           Casa
11      Alimentos
12         Livros
13      Alimentos
14         Livros
15      Vestuário
16      Alimentos
17         Livros
18      Vestuário
19      Alimentos
20      Alimentos
21         Livros
22    Eletrônicos
23           Casa
24      Vestuário
25           Casa
26    Eletrônicos
27      Vestuário
28           Casa
29         Livros
30           Casa
31           Casa
32    Eletrônicos
33         Livros
34    Eletrônicos
35      Vestuário
36      Alimentos
37      Vestuário
38         Livros
39      Alimentos
40         Livros
41           Casa
42         Livros
43         Livros
44      Alimentos
45    Eletrônicos
46           Casa
47    Eletrônicos
48    Eletrônicos
49           Casa
Name: Categoria do produto, dtype: object

In [5]:
df_produtos["Categoria do produto"].unique()

array(['Alimentos', 'Eletrônicos', 'Vestuário', 'Livros', 'Casa'],
      dtype=object)

In [6]:
set(df_produtos["Categoria do produto"])

{'Alimentos', 'Casa', 'Eletrônicos', 'Livros', 'Vestuário'}

# Filtrando elementos de um Pandas DataFrame

In [7]:
df_produtos[df_produtos["Categoria do produto"] == "Eletrônicos"]

,Nome do produto,Categoria do produto,Preço,Quantos produtos foram vendidos
3,Produto 4,Eletrônicos,714.87,18
6,Produto 7,Eletrônicos,139.07,23
22,Produto 23,Eletrônicos,834.25,17
26,Produto 27,Eletrônicos,81.65,96
32,Produto 33,Eletrônicos,751.86,64
34,Produto 35,Eletrônicos,444.46,31
45,Produto 46,Eletrônicos,177.61,34
47,Produto 48,Eletrônicos,387.29,83
48,Produto 49,Eletrônicos,708.58,57

In [8]:
df_produtos[df_produtos["Preço"] < 500]

,Nome do produto,Categoria do produto,Preço,Quantos produtos foram vendidos
0,Produto 1,Alimentos,406.86,55
1,Produto 2,Alimentos,347.76,16
4,Produto 5,Vestuário,162.54,81
5,Produto 6,Livros,337.71,51
6,Produto 7,Eletrônicos,139.07,23
10,Produto 11,Casa,244.32,73
11,Produto 12,Alimentos,496.19,70
12,Produto 13,Livros,60.49,32
13,Produto 14,Alimentos,40.84,49
14,Produto 15,Livros,398.58,20
15,Produto 16,Vestuário,127.23,15
18,Produto 19,Vestuário,225.58,49
19,Produto 20,Alimentos,316.94,14
21,Produto 22,Livros,187.36,95
23,Produto 24,Casa,340.26,60
24,Produto 25,Vestuário,291.40,59
26,Produto 27,Eletrônicos,81.65,96
30,Produto 31,Casa,43.57,38
33,Produto 34,Livros,36.93,51
34,Produto 35,Eletrônicos,444.46,31
39,Produto 40,Alimentos,412.83,9
40,Produto 41,Livros,148.77,49
42,Produto 43,Livros,206.29,32
43,Produto 44,Livros,421.72,91
45,Produto 46,Eletrônicos,177.61,34
47,Produto 48,Eletrônicos,387.29,83
49,Produto 50,Casa,274.10,32

In [9]:
df_produtos.shape

(50, 4)

In [10]:
df_produtos[(df_produtos["Categoria do produto"] == "Eletrônicos") & (df_produtos["Preço"] >= 350.0)]

,Nome do produto,Categoria do produto,Preço,Quantos produtos foram vendidos
3,Produto 4,Eletrônicos,714.87,18
22,Produto 23,Eletrônicos,834.25,17
32,Produto 33,Eletrônicos,751.86,64
34,Produto 35,Eletrônicos,444.46,31
47,Produto 48,Eletrônicos,387.29,83
48,Produto 49,Eletrônicos,708.58,57

# Métodos LOC e ILOC

In [11]:
df_produtos.iloc[15]

Nome do produto                    Produto 16
Categoria do produto                Vestuário
Preço                                  127.23
Quantos produtos foram vendidos            15
Name: 15, dtype: object

In [12]:
df_produtos.iloc[0:16]

,Nome do produto,Categoria do produto,Preço,Quantos produtos foram vendidos
0,Produto 1,Alimentos,406.86,55
1,Produto 2,Alimentos,347.76,16
2,Produto 3,Alimentos,541.36,76
3,Produto 4,Eletrônicos,714.87,18
4,Produto 5,Vestuário,162.54,81
5,Produto 6,Livros,337.71,51
6,Produto 7,Eletrônicos,139.07,23
7,Produto 8,Alimentos,921.66,82
8,Produto 9,Livros,502.67,92
9,Produto 10,Casa,754.53,11
10,Produto 11,Casa,244.32,73
11,Produto 12,Alimentos,496.19,70
12,Produto 13,Livros,60.49,32
13,Produto 14,Alimentos,40.84,49
14,Produto 15,Livros,398.58,20
15,Produto 16,Vestuário,127.23,15

Novo DF baseado em df_produtos mas que o índice é o nome

In [13]:
df_produtos_por_nome = df_produtos.set_index('Nome do produto')
display(df_produtos_por_nome.head())

                Categoria do produto   Preço  Quantos produtos foram vendidos
Nome do produto
Produto 1                  Alimentos  406.86                               55
Produto 2                  Alimentos  347.76                               16
Produto 3                  Alimentos  541.36                               76
Produto 4                Eletrônicos  714.87                               18
Produto 5                  Vestuário  162.54                               81

In [14]:
df_produtos_por_nome.loc["Produto 3"]

Categoria do produto               Alimentos
Preço                                 541.36
Quantos produtos foram vendidos           76
Name: Produto 3, dtype: object

In [15]:
df_produtos_por_nome.loc["Produto 3":"Produto 7"]

                Categoria do produto   Preço  Quantos produtos foram vendidos
Nome do produto
Produto 3                  Alimentos  541.36                               76
Produto 4                Eletrônicos  714.87                               18
Produto 5                  Vestuário  162.54                               81
Produto 6                     Livros  337.71                               51
Produto 7                Eletrônicos  139.07                               23

In [16]:
df_produtos_por_nome.loc["Produto 3", "Preço"]

np.float64(541.36)

In [17]:
df_produtos_por_nome.loc[["Produto 3","Produto 7","Produto 8"], ["Preço", "Quantos produtos foram vendidos"]]

                  Preço  Quantos produtos foram vendidos
Nome do produto
Produto 3        541.36                               76
Produto 7        139.07                               23
Produto 8        921.66                               82

In [22]:
eletronicos = df_produtos_por_nome[df_produtos_por_nome["Categoria do produto"] == "Eletrônicos"]
df_produtos_por_nome.loc[eletronicos.index, ["Preço", "Quantos produtos foram vendidos"]]

                  Preço  Quantos produtos foram vendidos
Nome do produto
Produto 4        714.87                               18
Produto 7        139.07                               23
Produto 23       834.25                               17
Produto 27        81.65                               96
Produto 33       751.86                               64
Produto 35       444.46                               31
Produto 46       177.61                               34
Produto 48       387.29                               83
Produto 49       708.58                               57

In [26]:
livros = df_produtos_por_nome[df_produtos_por_nome["Categoria do produto"] == "Livros"]
df_produtos_por_nome.loc[livros.index, "Categoria do produto"] = "Livros de terror"

In [27]:
df_produtos_por_nome

                Categoria do produto   Preço  Quantos produtos foram vendidos
Nome do produto
Produto 1                  Alimentos  406.86                               55
Produto 2                  Alimentos  347.76                               16
Produto 3                  Alimentos  541.36                               76
Produto 4                Eletrônicos  714.87                               18
Produto 5                  Vestuário  162.54                               81
Produto 6           Livros de terror  337.71                               51
Produto 7                Eletrônicos  139.07                               23
Produto 8                  Alimentos  921.66                               82
Produto 9           Livros de terror  502.67                               92
Produto 10                      Casa  754.53                               11
Produto 11                      Casa  244.32                               73
Produto 12                 Alimentos  496.19                               70
Produto 13          Livros de terror   60.49                               32
Produto 14                 Alimentos   40.84                               49
Produto 15          Livros de terror  398.58                               20
Produto 16                 Vestuário  127.23                               15
Produto 17                 Alimentos  837.55                               84
Produto 18          Livros de terror  811.72                               15
Produto 19                 Vestuário  225.58                               49
Produto 20                 Alimentos  316.94                               14
Produto 21                 Alimentos  724.89                               38
Produto 22          Livros de terror  187.36                               95
Produto 23               Eletrônicos  834.25                               17
Produto 24                      Casa  340.26                               60
Produto 25                 Vestuário  291.40                               59
Produto 26                      Casa  868.43                               34
Produto 27               Eletrônicos   81.65                               96
Produto 28                 Vestuário  749.30                               67
Produto 29                      Casa  707.14                               67
Produto 30          Livros de terror  726.63                               22
Produto 31                      Casa   43.57                               38
Produto 32                      Casa  732.54                               30
Produto 33               Eletrônicos  751.86                               64
Produto 34          Livros de terror   36.93                               51
Produto 35               Eletrônicos  444.46                               31
Produto 36                 Vestuário  759.70                               90
Produto 37                 Alimentos  754.83                               82
Produto 38                 Vestuário  667.40                               38
Produto 39          Livros de terror  874.98                               95
Produto 40                 Alimentos  412.83                                9
Produto 41          Livros de terror  148.77                               49
Produto 42                      Casa  988.52                               31
Produto 43          Livros de terror  206.29                               32
Produto 44          Livros de terror  421.72                               91
Produto 45                 Alimentos  989.18                               32
Produto 46               Eletrônicos  177.61                               34
Produto 47                      Casa  697.37                               20
Produto 48               Eletrônicos  387.29                               83
Produto 49               Eletrônicos  708.58                               57
Produto 50                      Casa  274.10                               32

Desafio:
1 carregar arquivo .csv com feedback de clientes, usar um LLM para classificar o sentimento de cada feedback (positivo, negativom, neutro) e adicionar essa classificacao ao dataframe